/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sil.ui;

import com.sil.dao.Reportes;

/**
 *
 * @author Adrian Floers
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuDatosGenerales = new javax.swing.JMenu();
        jMenuItemLicorerias = new javax.swing.JMenuItem();
        jMenuItemUsuarios = new javax.swing.JMenuItem();
        jMenuItemEmpleados = new javax.swing.JMenuItem();
        jMenuItemTipoProductos = new javax.swing.JMenuItem();
        jMenuOperaciones = new javax.swing.JMenu();
        jMenuItemProductos = new javax.swing.JMenuItem();
        jMenuItemInventario = new javax.swing.JMenuItem();
        jMenuItemMovimientos = new javax.swing.JMenuItem();
        jMenuReportesUsuarios = new javax.swing.JMenu();
        jMenuItemReporteUsuarios = new javax.swing.JMenuItem();
        jMenuItemReporteLicorerias = new javax.swing.JMenuItem();
        jMenuAyuda = new javax.swing.JMenu();
        jMenuAcerca = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Licoreria - Menu Principal");

        jMenuDatosGenerales.setText("Datos Generales");

        jMenuItemLicorerias.setText("Licorerias");
        jMenuItemLicorerias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLicoreriasActionPerformed(evt);
            }
        });
        jMenuDatosGenerales.add(jMenuItemLicorerias);

        jMenuItemUsuarios.setText("Usuarios");
        jMenuItemUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUsuariosActionPerformed(evt);
            }
        });
        jMenuDatosGenerales.add(jMenuItemUsuarios);

        jMenuItemEmpleados.setText("Empleados");
        jMenuDatosGenerales.add(jMenuItemEmpleados);

        jMenuItemTipoProductos.setText("Tipo Productos");
        jMenuItemTipoProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTipoProductosActionPerformed(evt);
            }
        });
        jMenuDatosGenerales.add(jMenuItemTipoProductos);

        jMenuBar1.add(jMenuDatosGenerales);

        jMenuOperaciones.setText("Operaciones");

        jMenuItemProductos.setText("Productos");
        jMenuItemProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemProductosActionPerformed(evt);
            }
        });
        jMenuOperaciones.add(jMenuItemProductos);

        jMenuItemInventario.setText("Inventario");
        jMenuOperaciones.add(jMenuItemInventario);

        jMenuItemMovimientos.setText("Movimientos");
        jMenuOperaciones.add(jMenuItemMovimientos);

        jMenuBar1.add(jMenuOperaciones);

        jMenuReportesUsuarios.setText("Reportes");

        jMenuItemReporteUsuarios.setText("Usuarios");
        jMenuItemReporteUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemReporteUsuariosActionPerformed(evt);
            }
        });
        jMenuReportesUsuarios.add(jMenuItemReporteUsuarios);

        jMenuItemReporteLicorerias.setText("Licorerias");
        jMenuItemReporteLicorerias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemReporteLicoreriasActionPerformed(evt);
            }
        });
        jMenuReportesUsuarios.add(jMenuItemReporteLicorerias);

        jMenuBar1.add(jMenuReportesUsuarios);

        jMenuAyuda.setText("Ayuda");
        jMenuAyuda.setActionCommand("Acerca...");

        jMenuAcerca.setText("Acerca de...");
        jMenuAyuda.add(jMenuAcerca);

        jMenuBar1.add(jMenuAyuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemLicoreriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLicoreriasActionPerformed
        // TODO add your handling code here: despliega menu licorerias

        OperacionesLicorerias ventanaLicorerias = new OperacionesLicorerias();

        ventanaLicorerias.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItemLicoreriasActionPerformed

    private void jMenuItemUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUsuariosActionPerformed
        // TODO add your handling code here: Aqui llamamos a la ventana de
        // Operaciones_Usuario

        OperacionesUsuarios ventanaRegistro = new OperacionesUsuarios();

        ventanaRegistro.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItemUsuariosActionPerformed

    private void jMenuItemTipoProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTipoProductosActionPerformed
        // TODO add your handling code here: Llama al menu Tipo Productos

        OperacionesTipoProductos tipoProductos = new OperacionesTipoProductos();

        this.dispose();
        tipoProductos.setVisible(true);
    }//GEN-LAST:event_jMenuItemTipoProductosActionPerformed

    private void jMenuItemReporteUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemReporteUsuariosActionPerformed
        // TODO add your handling code here: Llama al reporte de licorerias

        // ---------------- BUSCAR MANERA DE MANEJAR LAS CONEXION
        Reportes reporteUsuarios = new Reportes();

        reporteUsuarios.reportarUsuarios();
    }//GEN-LAST:event_jMenuItemReporteUsuariosActionPerformed

    private void jMenuItemReporteLicoreriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemReporteLicoreriasActionPerformed
        // TODO add your handling code here: Llama al reporte de usuarios

        // ---------------- BUSCAR MANERA DE MANEJAR LAS CONEXION
        Reportes reporteUsuarios = new Reportes();

        reporteUsuarios.reportarLicorerias();
    }//GEN-LAST:event_jMenuItemReporteLicoreriasActionPerformed

    private void jMenuItemProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemProductosActionPerformed
        // TODO add your handling code here:  Llama al menu Operaciones Productos

        OperacionesProductos operaProductos = new OperacionesProductos();

        this.dispose();
        operaProductos.setVisible(true);

    }//GEN-LAST:event_jMenuItemProductosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MenuPrincipal().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jMenuAcerca;
    private javax.swing.JMenu jMenuAyuda;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuDatosGenerales;
    private javax.swing.JMenuItem jMenuItemEmpleados;
    private javax.swing.JMenuItem jMenuItemInventario;
    private javax.swing.JMenuItem jMenuItemLicorerias;
    private javax.swing.JMenuItem jMenuItemMovimientos;
    private javax.swing.JMenuItem jMenuItemProductos;
    private javax.swing.JMenuItem jMenuItemReporteLicorerias;
    private javax.swing.JMenuItem jMenuItemReporteUsuarios;
    private javax.swing.JMenuItem jMenuItemTipoProductos;
    private javax.swing.JMenuItem jMenuItemUsuarios;
    private javax.swing.JMenu jMenuOperaciones;
    private javax.swing.JMenu jMenuReportesUsuarios;
    // End of variables declaration//GEN-END:variables
}
