/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sil.ui;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import com.sil.dao.Conexion;
import com.sil.dao.Usuarios;

/**
 * Esta clase es la ventana de registros de usuarios, se hace el llamado los
 * distintos metodos de la clase Usuarios.
 *
 * @author Adrian
 * @version 1
 */
public class OperacionesUsuarios extends javax.swing.JFrame {

    private final Conexion Conecta;
    private Connection Conector;
    private ResultSet Rs;
    private final Usuarios usuario;

    private final MenuPrincipal menuPrincipal;

    /**
     * Creates new form NewJFrame
     */
    public OperacionesUsuarios() {
        this.Conecta = new Conexion();
        this.usuario = new Usuarios();
        this.menuPrincipal = new MenuPrincipal();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblID = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblApellido = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextNombre = new javax.swing.JTextField();
        jTextUsuario = new javax.swing.JTextField();
        jPasswordClave = new javax.swing.JPasswordField();
        jPasswordRepiteClave = new javax.swing.JPasswordField();
        jButtonBuscar = new javax.swing.JButton();
        jButtonRegistrar = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblID.setText("Nombre:");

        lblNombre.setText("Usuario:");

        lblApellido.setText("Clave:");

        jLabel1.setText("Repetir clave:");

        jTextNombre.setColumns(10);

        jTextUsuario.setColumns(10);

        jButtonBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscar.gif"))); // NOI18N
        jButtonBuscar.setText("Buscar");
        jButtonBuscar.setToolTipText("Buscar usuario por Login");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        jButtonRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/calcular.gif"))); // NOI18N
        jButtonRegistrar.setText("Registrar");
        jButtonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarActionPerformed(evt);
            }
        });

        jButtonEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eliminar.gif"))); // NOI18N
        jButtonEliminar.setText("Eliminar");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });

        jButtonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrar.gif"))); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblID)
                        .addGap(18, 18, 18)
                        .addComponent(jTextNombre))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPasswordRepiteClave))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombre)
                            .addComponent(lblApellido))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPasswordClave)
                            .addComponent(jTextUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblID)
                    .addComponent(jTextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(jTextUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRegistrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApellido)
                    .addComponent(jPasswordClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEliminar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordRepiteClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jButtonCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        // TODO add your handling code here: buscar usuario en bd

        try {
            // Ejecuta el metodo otraBusqueda recibiendo como parametro el
            // contenido de jTextUsuario
            Rs = usuario.buscaUsuario(jTextUsuario.getText());
            // Si hay algun registro con la informacion ingresada en
            // jTextUsuario, mostrara los datos en las casillas nombre y usuario
            if (Rs.next()) {
                jTextNombre.setText(Rs.getString("nombreUsuarios"));
                jTextUsuario.setText(Rs.getString("login"));
            }
            // Cierra las consultas y conexiones si estan abiertas
            usuario.cierraConsultas();
        } catch (SQLException sqle) {
            Logger.getLogger(Usuarios.class.getName()).log(Level.SEVERE, null, sqle);
        }
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jButtonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarActionPerformed
        // TODO :
        /*
         * Inicia el proceso de registro, si algunos de los campos esta en
         * blanco se muestra la ventana que indica que campo esta vacio. Si
         * alguna de las contraseñas no coincide, muestra un mensaje de
	 * advertencia finalmente realiza el registro del usuario
         */

        if (jTextNombre.getText().equals("")) {
            JOptionPane.showMessageDialog(null, " No ha ingresado el nombre del ususario ", "¿Nombre de usuario?",
                    JOptionPane.ERROR_MESSAGE);
        } else if (jTextUsuario.getText().equals("")) {
            JOptionPane.showMessageDialog(null, " No ha ingresado el ususario ", "¿Usuario?",
                    JOptionPane.ERROR_MESSAGE);
        } else if (jPasswordClave.getText().equals(jPasswordRepiteClave.getText())) {
            usuario.registrarUsuario(jTextUsuario.getText(), jTextNombre.getText(), jPasswordClave.getText());
            jTextNombre.setText("");
            jTextUsuario.setText("");
            jPasswordClave.setText("");
            jPasswordRepiteClave.setText("");
            // Cierra las consultas y conexiones si estan abiertas
            usuario.cierraConsultas();
        } else {
            JOptionPane.showMessageDialog(null, "Las contraseñas no coincide", "Repita las contraseñas",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonRegistrarActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        // TODO add your handling code here: Borra usuarios de la base datos

        if (!jTextNombre.getText().equals("") || !jTextUsuario.getText().equals("")) {
            usuario.borrarUsuario(jTextUsuario.getText());
            jTextNombre.setText("");
            jTextUsuario.setText("");
            // Cierra las consultas y conexiones si estan abiertas
            usuario.cierraConsultas();
        } else {
            JOptionPane.showMessageDialog(null, "No hay datos para eliminar");
        }
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here: muestra la ventana del menu
        // principal y cierra todas las conexiones.
        this.dispose();
        usuario.cierraConsultas();
        menuPrincipal.setVisible(true);
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OperacionesUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new OperacionesUsuarios().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonRegistrar;
    private javax.swing.JLabel jLabel1;
    public static javax.swing.JPasswordField jPasswordClave;
    private javax.swing.JPasswordField jPasswordRepiteClave;
    public static javax.swing.JTextField jTextNombre;
    public static javax.swing.JTextField jTextUsuario;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblNombre;
    // End of variables declaration//GEN-END:variables
}
