/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sil.ui;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import com.sil.dao.Conexion;
import com.sil.dao.Tipos;

/**
 * class OperacionesTipoProductos:
 *
 * Esta clase es la ventana donde se procedera a realizar las operaciones de los
 * tipos de productos.
 *
 * @author Adrian
 */
public class OperacionesTipoProductos extends javax.swing.JFrame {

    // Parametos y variables de la clase
    private static final long serialVersionUID = 1L;

    private static final Conexion conecta = new Conexion();
    private static Connection Conector;
    private static Statement St;
    private static ResultSet Rs;
    //Cierre de declaracion de variables.

    /**
     * Metodo MostrarRegistros:
     *
     * Muestra en el combobox la lista de registros disponibles en la base de
     * datos
     */
    private void muestraTipos() {

        String Query = "SELECT descripcionTipo FROM sil.tipoproductos;";
        try {
            Conector = conecta.conectar();
            St = Conector.createStatement();
            Rs = St.executeQuery(Query);
            while (Rs.next()) {
                jComboTipos.addItem(Rs.getString("descripcionTipo"));
            }
            conecta.cerrarConexion();
            Rs.close();
        } catch (SQLException sqle) {
            JOptionPane.showMessageDialog(null, "Error en la consulta.");
            Logger.getLogger(OperacionesTipoProductos.class.getName()).log(Level.SEVERE, null, sqle);
        }
    }

    /**
     * Creates new form NewJFrame
     */
    public OperacionesTipoProductos() {
        initComponents();

        muestraTipos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelDescripcion = new javax.swing.JLabel();
        jLabelTipos = new javax.swing.JLabel();
        jTextTipo = new javax.swing.JTextField();
        jComboTipos = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jButtonRegistrar = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonSelecciona = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Matenimiento Tipos");

        jLabelDescripcion.setText("Descripcion:");

        jLabelTipos.setText("Tipos de Productos:");

        jTextTipo.setColumns(10);

        jComboTipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboTiposActionPerformed(evt);
            }
        });

        jButtonRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/grabar.gif"))); // NOI18N
        jButtonRegistrar.setText("Registrar");
        jButtonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarActionPerformed(evt);
            }
        });

        jButtonEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eliminar.gif"))); // NOI18N
        jButtonEliminar.setText("Eliminar");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });

        jButtonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrar.gif"))); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonSelecciona.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/VER.gif"))); // NOI18N
        jButtonSelecciona.setText("Seleccionar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonRegistrar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonEliminar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelTipos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboTipos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSelecciona))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabelDescripcion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jSeparator1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTipos)
                    .addComponent(jComboTipos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSelecciona))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDescripcion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEliminar)
                    .addComponent(jButtonRegistrar)
                    .addComponent(jButtonCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboTiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboTiposActionPerformed
        // TODO add your handling code here: Muestra en el jTextTipo la
        // seleccion que se haga en el jComboTipos

        jTextTipo.setText((String) jComboTipos.getSelectedItem());

        // MANEJO DE RECURSOS!!!! --- Este bloque no esta jodiento - DESCARTADO
    }//GEN-LAST:event_jComboTiposActionPerformed

    private void jButtonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarActionPerformed
        // TODO add your handling code here: agrega registros a la base de datos
        // mediante el metodo RegistrarTipos

        Tipos registraTipos = new Tipos();

        // Registra el registro jeje :P
        registraTipos.registrarTipo(jTextTipo.getText());

        // Actualiza la lista de registros
        jComboTipos.removeAllItems();
        muestraTipos();
        jTextTipo.setText("");

    }//GEN-LAST:event_jButtonRegistrarActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        // TODO add your handling code here: Elimina un registro de la base de
        // datos y muestra en el combobox los registros actuales

        Tipos eliminaRegistros = new Tipos();

        // Elimina el registro
        eliminaRegistros.eliminarTipo(jTextTipo.getText());

        // Actualiza la lista de registros
        jComboTipos.removeAllItems();
        muestraTipos();
        jTextTipo.setText("");

    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here: cierra la ventana actual y llama al
        // menu principal.

        MenuPrincipal menuPrincipal = new MenuPrincipal();

        this.dispose();
        menuPrincipal.setVisible(true);
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OperacionesLicorerias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new OperacionesTipoProductos().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonRegistrar;
    private javax.swing.JButton jButtonSelecciona;
    private javax.swing.JComboBox<String> jComboTipos;
    private javax.swing.JLabel jLabelDescripcion;
    private javax.swing.JLabel jLabelTipos;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextTipo;
    // End of variables declaration//GEN-END:variables
}
